#!/bin/bash


## System Checks
function check_deps(){
	if [ ! -x "$1" ]; then
		echo "ERROR: Missing dependency ${1}" 1>&2
		exit 1 
	fi
}

check_deps /usr/bin/git
check_deps /usr/bin/gh
if [ "$(uname -m)" != "aarch64" ]; then
	check_deps /usr/bin/qemu-arm-static
fi
check_deps /usr/bin/xz

apt install -y python3-git lsof

## Options
function usage() { echo "Usage: $0 -v VERSION" 1>&2; exit 1; }

while getopts "v:" opt; do
	case $opt in
		v) VER="$OPTARG" ;;
		*) usage ;;
	esac
done
shift $((OPTIND-1))

if [ -z "${VER}" ]; then
	usage
fi

## Error out immediately on any problem
set -e

## Clone the CustomPiOS Builder
git clone --depth 1 https://github.com/guysoft/CustomPiOS

## Generate the image build system
pushd CustomPiOS

# Install the patches for CustomPiOS
patch -p1 < ../aarch64_fixes.patch
patch -p1 < ../mod_net_quirks.patch

if [ -d asl3 ]; then
	echo "ERROR: Image structure asl3 already exists" 1>&2
	exit 1
fi

export USER=root 
./src/make_custom_pi_os -v raspios_lite_arm64 -g ./asl3
cp -r ../modules/* asl3/src/modules/
perl -pe "s/\@\@VER\@\@/${VER}/g" ../config > asl3/src/config

## Spin the image
pushd asl3/src
echo "export ASL3_REPO_LVL=\"${REPOLVL}\"" >> config

# Fix the image path - see https://github.com/guysoft/CustomPiOS/issues/243
mv image image-raspberrypiarm64

sudo ./build_dist
popd

echo "Compressing image... this takes a long time...."
IMGFILE=$(ls asl3/src/workspace/*.img)
xz -T 0 -c ${IMGFILE} > ../allstar3-arm64-${VER}.img.xz
popd

ls -l *.xz

## Copy to repo
echo "${SSH_REPO_AWS_PI_IMAGE_KEY}" > id_ed25519
chmod 600 id_ed25519
SSH_VARS="-i id_ed25519 -o StrictHostKeyChecking=accept-new"
scp ${SSH_VARS} allstar3-arm64-${VER}.img.xz aws-pi-builder@repo-admin.allstarlink.org:/var/www/html/images/pi
sha256sum allstar3-arm64-${VER}.img.xz > allstar3-arm64-${VER}.img.xz.sha256
scp ${SSH_VARS} allstar3-arm64-${VER}.img.xz.sha256 aws-pi-builder@repo-admin.allstarlink.org:/var/www/html/images/pi
