#!/bin/bash

set -x

## Copy to repo
echo "${SSH_REPO_AWS_PI_IMAGE_KEY}" > id_ed25519
chmod 600 id_ed25519

wc -l id_ed25519

dd if=/dev/zero of=testfile bs=1k count=1000

SSH_VARS="-i id_ed25519 -o StrictHostKeyChecking=accept-new"
scp -vvv ${SSH_VARS} testfile aws-pi-image@repo-admin.allstarlink.org:/var/www/html/images/pi
