#!/bin/bash

set -x

## Copy to repo
echo ${SSH_REPO_AWS_PI_IMAGE_KEY} > id_ed25519
chmod 600 id_ed25519

cat -E id_ed25519

#SSH_VARS="-i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new"
#scp ${SSH_VARS} allstar3-arm64-${VER}.img.xz aws-pi-image@repo-admin.allstarlink.org:/var/www/html/images/pi
#sha256sum allstar3-arm64-${VER}.img.xz > allstar3-arm64-${VER}.img.xz.sha256
#scp ${SSH_VARS} allstar3-arm64-${VER}.img.xz.sha256 aws-pi-image@repo-admin.allstarlink.org:/var/www/html/images/pi
