#!/usr/bin/env bash
# asl3/start_chroot_script
# Installs all of AllStarLink v3
# Written by Jason McCormick N8EI
# GPL V3
########


# Source error handling, leave this in place
set -e

source /common.sh
install_cleanup_trap

### noninteractive Check
if [ -z "${DEBIAN_FRONTEND}" ]; then
    export DEBIAN_FRONTEND=noninteractive
fi

# usr/local
unpack filesystem/usr/local/sbin/ /usr/local/sbin/ root

## Install AllStarLink Repo
wget -O/tmp/asl-apt-repos.deb13_all.deb \
	 https://repo.allstarlink.org/public/asl-apt-repos.deb13_all.deb
dpkg -i /tmp/asl-apt-repos.deb13_all.deb
rm -f /tmp/asl-apt-repos.deb13_all.deb

if [ ! -z "${A_R_S}" ]; then
	asl-repo-switch -l ${A_R_S}
fi

## Apt Updates
apt update
apt autoremove -y

# Cleanup old kernels, minimize size and number of DKMS builds needed
/usr/local/sbin/minimize-kernels \
	$(grep VERSION_CODENAME /etc/os-release | awk 'BEGIN {FS="="};{print $2}')

## Now Install ASL3
apt install -y asl3 asl3-menu allmon3 asl3-appliance-pi vim-nox

# Create motd & issue
unpack filesystem/etc /etc
echo "" > /etc/issue
echo "" > /etc/issue.net

# Set Firstboot
unpack filesystem/etc/systemd/system/ /etc/systemd/system/ root
touch /asl3-first-boot-needed
systemctl enable systemd-time-wait-sync.service
systemctl enable asl3-firstboot
systemctl enable asl3-firstboot-pkg-updates
systemctl enable asl3-firstboot-complete

# Disk IO minimization
rm -f /var/log/apache2/*
rm -rf /var/log/journal
rm -rf /var/log/asterisk/*

AST_UID=$(getent passwd asterisk | awk -F: '{print $3}')
AST_GID=$(getent passwd asterisk | awk -F: '{print $4}')
cat - >> /etc/fstab <<EOF

tmpfs	/tmp		tmpfs	defaults,noatime,nosuid,nodev,noexec,mode=1777,size=128M 0 0
tmpfs	/var/tmp	tmpfs	defaults,noatime,nosuid,nodev,noexec,mode=1777,size=128M 0 0

# Delete/comment out the next line for persistent Apache logs
tmpfs	/var/log/apache2	tmpfs	defaults,noatime,nosuid,nodev,noexec,mode=0775,size=32M 0 0

# Delete/comment out the next line for persistent Asterisk logs
tmpfs	/var/log/asterisk	tmpfs	defaults,noatime,nosuid,nodev,noexec,mode=0775,size=32M,uid=${AST_UID},gid=${AST_GID} 0 0 
EOF

## For GPIO accessibility, enable serial and disable bluetooth
cat - >> /boot/firmware/config.txt <<EOF
# ------------ Universal serial port on pins 8 / 10 -------------
[all]                     # applies to every Raspberry Pi model
enable_uart=1             # guarantees /dev/serial0 is created
dtoverlay=disable-bt      # kills the on-board BT radio
#  (on Pi 5 this is transparently remapped to the
#   Pi-5-specific overlay “disable-bt-pi5”)
# ---------------------------------------------------------------

EOF

