#!/usr/bin/bash

if [ $(uname -r) != "6.6.62+rpt-rpi-v8" ] && [ $(uname -r) != "6.6.62+rpt-rpi-2172" ]; then
	wget -O- https://repo.allstarlink.org/hotfix/asl3-pi12-kernel62-fix.sh | bash
else
	apt-mark hold linux-image-rpi-v8
	apt-mark hold linux-headers-rpi-2712
	apt-mark hold linux-headers-rpi-v8
	apt-mark hold linux-image-rpi-2712
fi

# do automated updates
DEBIAN_FRONTEND=noninteractive apt update -y
DEBIAN_FRONTEND=noninteractive apt dist-upgrade -y

# Disable firstboot
systemctl disable asl3-firstboot-pkg-updates
