#!/usr/bin/bash

if [ -e /asl3-first-boot-needed ]; then
	rm /asl3-first-boot-needed

	apt update -y
	apt dist-upgrade -y

	# Regenerate the snakeoil certificate	
	THISHOST=$(hostnamectl hostname)
	openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
	    -keyout /etc/ssl/private/ssl-cert-snakeoil.key \
    	-out /etc/ssl/certs/ssl-cert-snakeoil.pem -subj \
		"/CN=${THISHOST}.local"
	systemctl restart apache2

	# Regenerate the Cockpit certificate
	openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
        -keyout /etc/cockpit/ws-certs.d/0-self-signed.key
        -out /etc/cockpit/ws-certs.d/0-self-signed.cert -subj \
        "/CN=${THISHOST}.local"

	# Regenrate SSH keys 
	systemctl stop ssh
	rm /etc/ssh/ssh_host*key*
	ssh-keygen -A
	systemctl start ssh

	# Disable firstboot
	systemctl disable asl3-firstboot

fi

