name: 'Assemble Image'
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for ${{ inputs.os }}/${{ inputs.arch }}, Publish to ${{ inputs.deployment-environment }}
on: 
  workflow_dispatch:
    inputs:
      img-ver:
        description: 'Image version (e.g. 3.0.12)'
        type: string

env:
  SSH_REPO_AWS_PI_IMAGE_KEY: ${{secrets.SSH_REPO_AWS_PI_IMAGE_KEY}}


jobs:
  make-packages:
    uses: AllStarLink/asl3-pi-image/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: ./build-image -v ${{inputs.img-ver}}
    secrets: inherit
